name: Keep jeopardy.ashankbehara.com Render alive

on:
  schedule:
    # Run every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    environment: env  # Use the "env" environment created in repo settings
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Keep Render service alive
        env:
          RENDER_SERVICE_URL: ${{ secrets.JEOPARDY_RENDER_URL }}
        run: |
          # Ping the Render service to keep it active
          # This prevents the service from sleeping due to inactivity
          
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%S.%3NZ")
          
          echo "Sending heartbeat to Render service..."
          
          # Make a GET request to the health endpoint or root
          RESPONSE=$(curl -s -X GET \
            "${RENDER_SERVICE_URL}/health" \
            -H "User-Agent: GitHub-Actions-KeepAlive" \
            -w "%{http_code}" \
            --max-time 30 \
            --retry 3 \
            --retry-delay 5)
          
          HTTP_CODE="${RESPONSE: -3}"
          RESPONSE_BODY="${RESPONSE%???}"
          
          echo "Response code: $HTTP_CODE"
          echo "Response body: $RESPONSE_BODY"
          
          if [[ "$HTTP_CODE" == "200" ]] || [[ "$HTTP_CODE" == "201" ]] || [[ "$HTTP_CODE" == "204" ]]; then
            echo "✅ Render service pinged successfully"
          else
            echo "⚠️  Unexpected response code: $HTTP_CODE"
            # Don't fail the job for non-2xx responses as the service might still be alive
          fi
          
          echo "Render heartbeat completed at $TIMESTAMP"
      
      - name: Fallback ping to root endpoint
        if: failure()
        env:
          RENDER_SERVICE_URL: ${{ secrets.JEOPARDY_RENDER_URL }}
        run: |
          echo "Trying fallback ping to root endpoint..."
          
          RESPONSE=$(curl -s -X GET \
            "${RENDER_SERVICE_URL}/" \
            -H "User-Agent: GitHub-Actions-KeepAlive-Fallback" \
            -w "%{http_code}" \
            --max-time 30 \
            --retry 2 \
            --retry-delay 3)
          
          HTTP_CODE="${RESPONSE: -3}"
          
          echo "Fallback response code: $HTTP_CODE"
          
          if [[ "$HTTP_CODE" == "200" ]] || [[ "$HTTP_CODE" == "201" ]] || [[ "$HTTP_CODE" == "204" ]]; then
            echo "✅ Fallback ping successful"
          else
            echo "ℹ️  Service responded with code: $HTTP_CODE (service may still be alive)"
          fi 